.github/workflows/ci.yaml
package-lock.json
package.json
src/command/root-command.ts
src/command/upload.ts

Refactor based on `Bee 0.5.0` changes

refactor: new bee release

---

README.md

This is based on the branch `feat/feed` to make the review easier.
Closes #20

docs: add usage to README

---

README.md
src/command/root-command/command-config.ts
src/command/root-command/index.ts
test/command/cheque.spec.ts

feat: bee debug api url config and env

---

src/command/pinning/list.ts
src/command/pinning/pin.ts
src/command/pinning/pinning-command.ts
src/command/pinning/unpin.ts
src/command/upload.ts
src/utils/index.ts

This PR adds more user friendly error messages when trying to use pinning related functions with the gateway.

feat: pinning gateway handling

---

.github/workflows/ci.yaml

Add [Bee Factory](https://github.com/ethersphere/bee-factory) CI environment for Bee 0.6.0 tests

ci: bee factory

---

.github/workflows/ci.yaml
src/command/cheque/balance.ts
src/command/cheque/cashout.ts
src/command/cheque/cheque-command.ts
src/command/cheque/deposit.ts
src/command/cheque/list.ts
src/command/cheque/withdraw.ts
src/command/stamp/buy.ts
test/command/cheque.spec.ts
test/misc/monetary-units.spec.ts

Adds `PLUR` unit where applicable.
Also adds `wei` to `gas-price` option.
Adds 8 tests which check printed messages as well as help texts.

docs: monetary units

---

.github/workflows/ci.yaml
package-lock.json
package.json
src/command/cheque/deposit.ts
src/command/cheque/withdraw.ts
src/command/status.ts
src/config.ts
test/command/status.spec.ts

feat: status command

---

README.md
src/command/feed/feed-command.ts
src/command/feed/print.ts
src/command/pss/index.ts
src/command/pss/pss-command.ts
src/command/pss/receive.ts
src/command/pss/send.ts
src/command/pss/subscribe.ts
src/config.ts
src/utils/index.ts
test/command/pss.spec.ts
test/testconfig/.gitignore

```
█ Available Commands:
pss send        Send to recipient or target with Postal Service for Swarm
pss receive     Receive message with Postal Service for Swarm
pss subscribe   Subscribe to messages with Postal Service for Swarm
```

feat: add pss commands

---

README.md
src/command/stamp/list.ts
src/command/stamp/show.ts
src/command/stamp/stamp-command.ts
src/service/stamp/index.ts
src/service/stamp/types/stamp.ts
test/command/stamp.spec.ts

feat: add stamp usage, sorting and filtering

---

src/command/upload.ts
test/command/upload.spec.ts

Adds `--encrypt` boolean option to `upload` command

feat: add --encrypt to upload

---

package-lock.json
package.json
src/command/addresses.ts
src/command/cheque/cashout.ts
src/command/cheque/cheque-command.ts
src/command/identity/remove.ts
src/command/root-command/command-log.ts
src/command/root-command/printer.ts
src/command/status.ts
src/command/upload.ts
src/printer.ts
src/utils/spinner.ts
src/utils/text.ts

- Changed green question mark to cyan in prompts (#203)
- Hexagon spinner is now orange
- Replaced `kleur` with `chalk`

feat: establish color system with chalk

---

package-lock.json
package.json
src/command/feed/feed-command.ts
src/command/root-command/index.ts
src/command/stamp/buy.ts
src/command/upload.ts
src/config.ts
src/curl.ts
test/misc/curl.spec.ts

Adds `--curl` global option using the new `bee-js` *Hooks* feature for debug purposes.

feat: add --curl global option

---

package.json
webpack.config.ts

```
npm pack                               
```
```
npm notice 
npm notice 📦  @ethersphere/swarm-cli@1.5.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE      
npm notice 15.8kB README.md    
npm notice 1.6MB  dist/index.js
npm notice 2.7kB  package.json 
npm notice === Tarball Details === 
npm notice name:          @ethersphere/swarm-cli                  
npm notice version:       1.5.0                                   
npm notice filename:      @ethersphere/swarm-cli-1.5.0.tgz        
npm notice package size:  563.3 kB                                
npm notice unpacked size: 1.6 MB                                  
npm notice shasum:        b4d0c152a4929848fb9cb23d213d069522f006b7
npm notice integrity:     sha512-+ip3eqnSdnWaC[...]DRdVR1Y6PlOJg==
npm notice total …
```

build: optimize npm pack

---

src/command/manifest/download.ts
test/command/download.spec.ts
test/command/manifest.spec.ts

https://user-images.githubusercontent.com/77121044/140074917-b8ad3251-1c13-4136-b85f-8acccbf19ffa.mov

refactor: improve download progress and add spinner

---

.github/workflows/check.yaml
.github/workflows/release_github.yaml

This PR consolidates secrets variables, we defined some org wide variables and from now on we will rotate and manage those variables more easily

replace REPO_GHA_PAT with GHA_PAT_BASIC

---

src/command/stamp/buy.ts
src/utils/index.ts
test/command/stamp.spec.ts
test/prompt/stamp-prompt.spec.ts
test/utility/stamp.ts
test/utils/index.spec.ts

feat: calculate and show stamp cost

---

.gitignore
src/command/feed/print.ts
test/quality-of-life/topic.spec.ts

fix: spinner on feed print command

---

src/service/stamp/index.ts
src/utils/index.ts
test/prompt/feed-prompt.spec.ts
test/utility/stamp.ts
test/utils/index.spec.ts

feat: improve stamp ttl display and exclude expired stamps

---

src/command/manifest/sync.ts

The manifest sync command uses bmt-js to check changes instead of downloading all files.
Closes #489

feat: manifest sync improvement (#489)

---

src/command/feed/print.ts

fix: support identity in feed print

---

src/utils/option.ts

Closes https://github.com/ethersphere/swarm-cli/issues/359

feat: allow setting default stamp with stamp env
