ethersphere/swarm-cli

.eslintrc.js, .prettierrc.json
There were some problems with the eslint/prettier configuration, that prevented to do auto-formatting.
this PR solves this problem
=> style: add prettier autoformats to eslint

.github/workflows/ci.yaml
As per the nodejs release cycle, we should support node v15 as well https://nodejs.org/en/about/releases/
=> ci: add node v15 as test target

.github/workflows/publish_npmjs.yaml, .github/workflows/release_github.yaml, package.json
For more info and how to use please see https://github.com/ethersphere/bee-js/pull/70
=> ci: release on github and npmjs

.vscode/launch.json, .vscode/settings.json, README.md, package-lock.json, package.json, src/command/command-config.ts, src/command/identity/create.ts, src/command/identity/index.ts, src/command/identity/list.ts, src/command/identity/remove.ts, src/command/root-command.ts, src/command/upload.ts, src/config.ts, src/index.ts, src/service/identity/index.ts, src/service/identity/types/identity.ts, src/service/identity/types/index.ts, src/service/identity/types/wallet.ts, src/utils/console-log.ts, src/utils/hex.ts, src/utils/prompt.ts, src/utils/types/index.ts, test/command/identity.spec.ts, test/testconfig/.gitignore, webpack.config.ts
This PR adds `identity` commands to the CLI.
It handles wallets of the user, which will be mostly used for sign chunks.
Config feature also has been added, in order to store wallets on the user's computer.
The configuration file is placed in a hidden folder named `swarm-cli`.
In case of Unix-based systems this config path will be: `$HOME/.swarm-cli`
On Windows systems: `$HOME\AppData\swarm-cli`
The configuration file is saved with 600 file permission.
There are two types of wallets currently in this feat PR: `simple` and `V3 keystore`.
- The first only generates a private key, that it will store in the config fire in cleartext. These can be generated quickly.
- The latter is Ethereum compatible wallet, which fits to the `V3` standard. Its creation is slower and also requires a password. …
=> feat: identity

src/command/upload.ts
Added a new `--skip-sync` flag to `upload` and `feed upload`.
It disables tags and waiting for network synchronisation.
Using this option makes it possible to upload to the public gateway.
=> feat: add --skip-sync flag to upload and feed upload

src/command/pinning/pin.ts, src/command/pinning/unpin.ts, test/command/pinning.spec.ts
Checking for `Internal Server Error` during `pinning unpin` was a mistake originally. It either returns `Not Found` or `Bad Request`. This PR handles these cases with a nicer error message and adds a test case for that.
In `pinning pin`, `Internal Server Error` is correct, but the `Not Found` case also exists there which was not handled. This PR also adds that with a test.
=> fix: handle not found and bad request pinning errors

src/command/cheque/cashout.ts, src/command/cheque/cheque-command.ts, src/command/cheque/list.ts
Some `cheque` commands inherited the `--minimum` option.
Examples:
```
balance
withdraw
deposit
```
It is only used in:
```
cashout
list
```
=> fix: remove --minimum option where it makes no sense

src/command/cheque/index.ts, src/command/feed/index.ts, src/command/identity/index.ts, src/command/pinning/index.ts
The goal here is to provide a bit nicer descriptions to command groups. Instead of simply saying _utilities_ or _interface_, or printing only _Cheque_, try to write a few examples with better wording.
Before
```
index.js pinning        - Pinning utilities
index.js identity       - Keypair management interface
index.js feed           - Feed utilities
index.js cheque         - Cheque
```
After
```
pinning    Pin, unpin and check pinned chunks
identity   Import, export and manage keypairs, identities
feed       Upload, update and view feeds
cheque     Deposit, withdraw and manage cheques
```
=> docs: unify group descriptions

src/command/root-command/command-log.ts, src/command/root-command/printer.ts, src/printer.ts
Continuation of https://github.com/ethersphere/swarm-cli/pull/79#discussion_r623905757
This PR extracts the different `console.log` printing methods so they can be used without instantiation.
They are used to construct `CommandLog` as well as `Printer` for furious-commander.
=> refactor: extract printing functions to avoid instantiation

.github/workflows/ci.yaml
from now `BEE_VERSION` and `BLOCKCHAIN_VERSION` Bee Factory parameters in CI will use the [.env](https://github.com/ethersphere/bee-factory/blob/master/scripts/.env) definitions according to the chosen branch.
=> ci: bee factory parameters

test/command/cheque.spec.ts, test/command/feed.spec.ts, test/command/identity.spec.ts, test/command/pinning.spec.ts, test/command/stamp.spec.ts, test/command/upload.spec.ts, test/utility/index.ts, test/utility/stamp.ts
Replace
```
await cli({
rootCommandClasses,
optionParameters,
testArguments: argv,
})
```
with
```
await invokeTestCli(argv)
```
=> refactor(test): shorten cli calls

src/command/root-command/command-config.ts, src/command/root-command/index.ts, src/config.ts, src/utils/types/config-option.ts, test/command/config.spec.ts, test/misc/config.spec.ts
Continuation of https://github.com/ethersphere/swarm-cli/pull/79#discussion_r623898323
Instead of having duplicated `if` blocks for each option that may be specified via the swarm-cli config file, we just have to maintain an array: `CONFIG_OPTIONS`.
=> refactor: simplify reading config via sourcemap

package-lock.json, package.json, src/command/feed/feed-command.ts, src/command/feed/print.ts, src/command/feed/update.ts, src/command/feed/upload.ts, src/command/root-command/command-log.ts, src/command/stamp/show.ts, src/command/upload.ts, src/service/stamp/index.ts
`--stamp` options can be interactively picked from the currently available stamp list.
---
Will also include new `furious-commander` version which brings enhancements:
* Conflicting options are printed in help
* `noErrors` property for tolerating missing required options and arguments (for Stamp Picker)
=> feat: core update and stamp picker

package.json
`@ethersphere/swarm-cli` as the bin name is invalid. Path separator should not be used in bin name. So remove it.
Giving yarn's error message as a reference:
```
warning @ethersphere/swarm-cli@0.7.0: Invalid bin entry for "@ethersphere/swarm-cli" (in "@ethersphere/swarm-cli").
```
=> fix: remove invalid bin field

src/command/pinning/index.ts, src/command/pinning/reupload-all.ts, test/command/pinning.spec.ts
Adds command `pinning reupload-all`.
Ideally it would be `pinning reupload --all`, but the parser does not support conflicts between positional arguments and options. We can iterate on it very soon in the future though.
Alternatively, I can do `reupload --all` and `reupload --chunk <address>` if we want to keep them in one command.
=> feat: add pinning reupload-all

test/command/cheque.spec.ts, test/command/feed.spec.ts, test/command/identity.spec.ts, test/command/pinning.spec.ts, test/command/pss.spec.ts, test/command/stamp.spec.ts, test/command/status.spec.ts, test/command/upload.spec.ts, test/misc/config.spec.ts, test/misc/monetary-units.spec.ts, test/prompt/feed-prompt.spec.ts, test/quality-of-life/numerical.spec.ts, test/quality-of-life/topic.spec.ts, test/utility/index.ts
Every test had the same init for console logs and config setups, this PR extract this into the `describeCommand` test utility function to maintain clearer test files.
=> refactor(test): describe command

README.md, src/command/root-command/printer.ts, src/command/status.ts
[Preview the README](https://github.com/ethersphere/swarm-cli/blob/98dcb2cf0ad806d6e38653c75dad0d6f8c13f182/README.md)
- Fixes writing errors to stderr
- Sets exit code to `1` when `status` has failures
- Changes description tagline to match Swarm-CLI tagline
- Adds Automation section 
- Adds Table of Contents
=> docs: add automation examples

src/command/addresses.ts, src/config.ts, test/command/addresses.spec.ts
The idea for `--quiet` mode is that `awk { print $2 }` would always be the address
=> feat: add addresses command

.gitignore, jest.config.ts, package-lock.json, package.json, src/command/upload.ts, test/command/upload.spec.ts
In `--verbose` mode, file or folder size is printed before uploading:
```
Upload size is approximately 2.00 megabytes
```
---
When upload size is too large:
```
? Folder size is larger than recommended value. Do you want to proceed? (Y/n) 
```
---
Fails in `--quiet` mode without explicit flag:
```
swarm-cli upload dist -q --stamp ...
Folder size is larger than recommended value.
Pass --size-check false to ignore this warning.
```
---
Needs to be disabled with `--size-check false`
=> feat: add upload size prompt/warning/flag

src/command/feed/feed-command.ts, src/command/feed/upload.ts, src/command/stamp/list.ts, src/command/stamp/show.ts, src/command/stamp/stamp-command.ts, src/command/upload.ts, src/service/stamp/index.ts, test/command/feed.spec.ts, test/command/pinning.spec.ts, test/command/upload.spec.ts, test/utility/index.ts
* Adds `--drop-name` flag to erase file name during upload
* Print stamp usage after `upload`, `feed print` and `feed upload`
* Change upload bar from `processed` to `synced` which works when reading file to memory
=> feat: add --drop-name to upload, print stamp after usage, sync progress

src/command/cheque/cashout.ts
Otherwise transactions were created for cashing out zero valued cheques.
I couldn't really test this, so take it more as a suggestion than a well-tested PR.
=> fix(cashout): set minimum of minimum to 1

src/command/upload.ts, src/config.ts, src/utils/text.ts, test/command/feed.spec.ts, test/command/pinning.spec.ts, test/command/upload.spec.ts, test/misc/curl.spec.ts
Removed `--skip-sync`, added `--sync`, and `--sync` is now opt-in
---
When debug API is not available:
---
When there are no connected peers:
---
Prompts have been removed, only a warning message is displayed.
=> feat: rework --skip-sync to --sync with connectivity check

src/command/upload.ts
Fixes https://github.com/ethersphere/swarm-cli/issues/365
=> fix: do not print bzz.link when uploading with encryption

src/service/stamp/index.ts, src/utils/index.ts
Referring issue
#355 
Added a util method to convert seconds to time human-readable format DHMS
=> fix: convert TTL to human readable format

src/command/manifest/index.ts, src/command/manifest/remove.ts
Enables all manifest commands and fixes unintentional file deletion by prompting user to confirm.
Closes #253
=> fix: manifest commands

src/command/root-command/index.ts, src/config.ts
`--dev` global option indicate that the connected Bee node is running in dev mode.
=> feat: add --dev global option
